### ISSUE TITLE
Seems to support ICC V.2 only.

### ISSUE THREAD

**Issue by Valentia** [SeanHayes/firefox-color-management-add-on#7]
If you look at this page http://www.color.org/version4html.xalter you will see that this add-on is not working correctly. Either that or Firefox CM is not set up correctly. Any ideas Sean?

Danny

**Comment by SeanHayes** [comment]
This extension only lets you modify the built in CM options in Firefox and is dependent on them.

The CM code in FF 3.0 supported ICC v4, but I guess due to bugs, speed, and/or stability issues they moved to another CM codebase in FF 3.5 which solved a lot of problems but only supports ICC v2 profiles. There's currently a bug filed with Mozilla for the new CM code to support ICC v4: https://bugzilla.mozilla.org/show_bug.cgi?id=488800.

Thanks for taking the time to file this bug.

**Comment by SeanHayes** [comment]
More info: http://muizelaar.blogspot.com/2009/06/qcms-color-management-for-web.html
